# Generated by Django 5.2.1 on 2025-06-02 02:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_material', models.CharField(choices=[('PAP', 'Papel y cartón'), ('PLAS', 'Plásticos reciclables'), ('VID', 'Vidrios'), ('LAT', 'Latas'), ('ELEC', 'Electrónicos pequeños'), ('TEX', 'Textiles'), ('VOL', 'Voluminosos reciclables')], max_length=10)),
                ('cantidad', models.IntegerField()),
                ('fecha_estimada', models.DateField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_ruta', 'En ruta'), ('completada', 'Completada')], default='pendiente', max_length=20)),
                ('comentario_operario', models.TextField(blank=True, null=True)),
                ('ciudadano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('operario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asignadas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
